PASSWORD_ERROR_MESSAGE = "Password not Match."
LOGIN_ERROR_MESSAGE = "Enter valid username or password."
REGISTER_SUCCESS_MESSAGE = "Register successfully"
LOGIN_SUCCESS_MESSAGE = "Successfully logged in."
LOGOUT_MESSAGE = "Successfully Logout"
