# Generated by Django 4.2.4 on 2023-08-28 13:05

from django.db import migrations
from django.contrib.auth.models import Group

def create_groups(apps,schema_editor):
    GROUP_CHOICES = ["Admin", "Project Manager", "Developer"]
    for group_name in GROUP_CHOICES:
        group, created = Group.objects.get_or_create(name=group_name)
        group.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_groups),
    ]
