# Generated by Django 4.2.4 on 2023-09-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clickup", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="assign",
            new_name="assignee",
        ),
    ]
